language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle isort pylint yapf
script:
  - isort --diff --check --recursive sshpubkeys tests
  - pycodestyle --ignore E501,E402 --exclude=.git,dev3 sshpubkeys tests
  - pylint sshpubkeys tests 
  - isort --recursive sshpubkeys tests; yapf --recursive .
  - git diff --exit-code  # This fails if isort&yapf combo made any changes
  - python setup.py test
